#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/jason

PRODUCT_COPY_FILES += \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/jason/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/jason/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/camera/jason_imx386_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jason_imx386_ofilm_chromatix.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/camera/jason_imx386_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jason_imx386_semco_chromatix.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/camera/jason_s5k3m3_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jason_s5k3m3_ofilm_chromatix.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/camera/jason_s5k3m3_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jason_s5k3m3_semco_chromatix.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/camera/jason_s5k3p8sp_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jason_s5k3p8sp_sunny_chromatix.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/hdr_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_config.cfg \
    vendor/xiaomi/jason/proprietary/vendor/etc/qdcm_calib_data_jdi_fhd_cmd_incell_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_fhd_cmd_incell_dsi_panel.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/qdcm_calib_data_sharp_fhd_cmd_incell_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sharp_fhd_cmd_incell_dsi_panel.xml \
    vendor/xiaomi/jason/proprietary/vendor/etc/sdr_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/sdr_config.cfg \
    vendor/xiaomi/jason/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/jason/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/jason/proprietary/vendor/etc/thermal-engine-sdm660-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-high.conf \
    vendor/xiaomi/jason/proprietary/vendor/etc/thermal-engine-sdm660-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-map.conf \
    vendor/xiaomi/jason/proprietary/vendor/etc/thermal-engine-sdm660-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-nolimits.conf \
    vendor/xiaomi/jason/proprietary/vendor/etc/thermal-engine-sdm660.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660.conf \
    vendor/xiaomi/jason/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/jason/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/xiaomi/jason/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/jason/proprietary/vendor/firmware/jason_bu63169_ofilm.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/jason_bu63169_ofilm.coeff \
    vendor/xiaomi/jason/proprietary/vendor/firmware/jason_bu63169_ofilm.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/jason_bu63169_ofilm.prog \
    vendor/xiaomi/jason/proprietary/vendor/firmware/jason_bu63169_semco.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/jason_bu63169_semco.coeff \
    vendor/xiaomi/jason/proprietary/vendor/firmware/jason_bu63169_semco.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/jason_bu63169_semco.prog

PRODUCT_PACKAGES += \
    libremosaic_daemon \
    libremosaiclib \
    libsensor1 \
    libsensor_reg \
    libthermalclient \
    sensors.ssc \
    libSonyIMX386PdafLibrary \
    libactuator_jason_imx386_ak7372_semco \
    libactuator_jason_imx386_ak7374_ofilm \
    libactuator_jason_s5k3m3_ak7372_semco \
    libactuator_jason_s5k3m3_ak7374_ofilm \
    libarcsoft_dualcam_optical_zoom \
    libarcsoft_dualcam_optical_zoom_control \
    libarcsoft_dualcam_refocus \
    libchromatix_jason_imx386_ofilm_4K_preview \
    libchromatix_jason_imx386_ofilm_4K_video \
    libchromatix_jason_imx386_ofilm_common \
    libchromatix_jason_imx386_ofilm_cpp_hfr_120 \
    libchromatix_jason_imx386_ofilm_cpp_hfr_60 \
    libchromatix_jason_imx386_ofilm_cpp_hfr_90 \
    libchromatix_jason_imx386_ofilm_cpp_liveshot \
    libchromatix_jason_imx386_ofilm_cpp_preview \
    libchromatix_jason_imx386_ofilm_cpp_snapshot \
    libchromatix_jason_imx386_ofilm_cpp_snapshot_hdr \
    libchromatix_jason_imx386_ofilm_cpp_video \
    libchromatix_jason_imx386_ofilm_cpp_video_hdr \
    libchromatix_jason_imx386_ofilm_default_preview \
    libchromatix_jason_imx386_ofilm_default_video \
    libchromatix_jason_imx386_ofilm_hdr_snapshot_3a \
    libchromatix_jason_imx386_ofilm_hdr_video_3a \
    libchromatix_jason_imx386_ofilm_hfr_120 \
    libchromatix_jason_imx386_ofilm_hfr_120_3a \
    libchromatix_jason_imx386_ofilm_hfr_60 \
    libchromatix_jason_imx386_ofilm_hfr_60_3a \
    libchromatix_jason_imx386_ofilm_hfr_90 \
    libchromatix_jason_imx386_ofilm_hfr_90_3a \
    libchromatix_jason_imx386_ofilm_liveshot \
    libchromatix_jason_imx386_ofilm_postproc \
    libchromatix_jason_imx386_ofilm_preview \
    libchromatix_jason_imx386_ofilm_snapshot \
    libchromatix_jason_imx386_ofilm_snapshot_hdr \
    libchromatix_jason_imx386_ofilm_video \
    libchromatix_jason_imx386_ofilm_video_hdr \
    libchromatix_jason_imx386_ofilm_zsl_preview \
    libchromatix_jason_imx386_ofilm_zsl_video \
    libchromatix_jason_imx386_semco_4K_preview \
    libchromatix_jason_imx386_semco_4K_video \
    libchromatix_jason_imx386_semco_common \
    libchromatix_jason_imx386_semco_cpp_hfr_120 \
    libchromatix_jason_imx386_semco_cpp_hfr_60 \
    libchromatix_jason_imx386_semco_cpp_hfr_90 \
    libchromatix_jason_imx386_semco_cpp_liveshot \
    libchromatix_jason_imx386_semco_cpp_preview \
    libchromatix_jason_imx386_semco_cpp_snapshot \
    libchromatix_jason_imx386_semco_cpp_snapshot_hdr \
    libchromatix_jason_imx386_semco_cpp_snapshot_hht \
    libchromatix_jason_imx386_semco_cpp_video \
    libchromatix_jason_imx386_semco_cpp_video_hdr \
    libchromatix_jason_imx386_semco_cpp_video_refiner \
    libchromatix_jason_imx386_semco_default_preview \
    libchromatix_jason_imx386_semco_default_video \
    libchromatix_jason_imx386_semco_hdr_snapshot_3a \
    libchromatix_jason_imx386_semco_hdr_video_3a \
    libchromatix_jason_imx386_semco_hfr_120 \
    libchromatix_jason_imx386_semco_hfr_120_3a \
    libchromatix_jason_imx386_semco_hfr_60 \
    libchromatix_jason_imx386_semco_hfr_60_3a \
    libchromatix_jason_imx386_semco_hfr_90 \
    libchromatix_jason_imx386_semco_hfr_90_3a \
    libchromatix_jason_imx386_semco_liveshot \
    libchromatix_jason_imx386_semco_postproc \
    libchromatix_jason_imx386_semco_preview \
    libchromatix_jason_imx386_semco_snapshot \
    libchromatix_jason_imx386_semco_snapshot_hdr \
    libchromatix_jason_imx386_semco_video \
    libchromatix_jason_imx386_semco_video_hdr \
    libchromatix_jason_imx386_semco_zsl_hdr_preview \
    libchromatix_jason_imx386_semco_zsl_preview \
    libchromatix_jason_imx386_semco_zsl_video \
    libchromatix_jason_s5k3m3_ofilm_1080p_preview_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_1080p_video_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_4k_preview_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_4k_video_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_common \
    libchromatix_jason_s5k3m3_ofilm_cpp_hfr_120 \
    libchromatix_jason_s5k3m3_ofilm_cpp_hfr_60 \
    libchromatix_jason_s5k3m3_ofilm_cpp_hfr_90 \
    libchromatix_jason_s5k3m3_ofilm_cpp_liveshot \
    libchromatix_jason_s5k3m3_ofilm_cpp_preview \
    libchromatix_jason_s5k3m3_ofilm_cpp_snapshot \
    libchromatix_jason_s5k3m3_ofilm_cpp_snapshot_downscale \
    libchromatix_jason_s5k3m3_ofilm_cpp_snapshot_upscale \
    libchromatix_jason_s5k3m3_ofilm_cpp_video \
    libchromatix_jason_s5k3m3_ofilm_cpp_video_4k \
    libchromatix_jason_s5k3m3_ofilm_default_preview_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_default_video \
    libchromatix_jason_s5k3m3_ofilm_default_video_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_hfr_120 \
    libchromatix_jason_s5k3m3_ofilm_hfr_120_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_hfr_60 \
    libchromatix_jason_s5k3m3_ofilm_hfr_60_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_hfr_90 \
    libchromatix_jason_s5k3m3_ofilm_hfr_90_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_liveshot \
    libchromatix_jason_s5k3m3_ofilm_postproc \
    libchromatix_jason_s5k3m3_ofilm_preview \
    libchromatix_jason_s5k3m3_ofilm_snapshot \
    libchromatix_jason_s5k3m3_ofilm_video_4k \
    libchromatix_jason_s5k3m3_ofilm_zsl_preview_ad5816g \
    libchromatix_jason_s5k3m3_ofilm_zsl_video_ad5816g \
    libchromatix_jason_s5k3m3_semco_1080p_preview_ad5816g \
    libchromatix_jason_s5k3m3_semco_1080p_video_ad5816g \
    libchromatix_jason_s5k3m3_semco_4k_preview_ad5816g \
    libchromatix_jason_s5k3m3_semco_4k_video_ad5816g \
    libchromatix_jason_s5k3m3_semco_common \
    libchromatix_jason_s5k3m3_semco_cpp_hfr_120 \
    libchromatix_jason_s5k3m3_semco_cpp_hfr_60 \
    libchromatix_jason_s5k3m3_semco_cpp_hfr_90 \
    libchromatix_jason_s5k3m3_semco_cpp_liveshot \
    libchromatix_jason_s5k3m3_semco_cpp_preview \
    libchromatix_jason_s5k3m3_semco_cpp_snapshot \
    libchromatix_jason_s5k3m3_semco_cpp_snapshot_downscale \
    libchromatix_jason_s5k3m3_semco_cpp_snapshot_hdr \
    libchromatix_jason_s5k3m3_semco_cpp_snapshot_hht \
    libchromatix_jason_s5k3m3_semco_cpp_snapshot_upscale \
    libchromatix_jason_s5k3m3_semco_cpp_video \
    libchromatix_jason_s5k3m3_semco_cpp_video_4k \
    libchromatix_jason_s5k3m3_semco_default_preview_ad5816g \
    libchromatix_jason_s5k3m3_semco_default_video \
    libchromatix_jason_s5k3m3_semco_default_video_ad5816g \
    libchromatix_jason_s5k3m3_semco_hfr_120 \
    libchromatix_jason_s5k3m3_semco_hfr_120_ad5816g \
    libchromatix_jason_s5k3m3_semco_hfr_60 \
    libchromatix_jason_s5k3m3_semco_hfr_60_ad5816g \
    libchromatix_jason_s5k3m3_semco_hfr_90 \
    libchromatix_jason_s5k3m3_semco_hfr_90_ad5816g \
    libchromatix_jason_s5k3m3_semco_liveshot \
    libchromatix_jason_s5k3m3_semco_postproc \
    libchromatix_jason_s5k3m3_semco_preview \
    libchromatix_jason_s5k3m3_semco_snapshot \
    libchromatix_jason_s5k3m3_semco_snapshot_hdr \
    libchromatix_jason_s5k3m3_semco_snapshot_hht \
    libchromatix_jason_s5k3m3_semco_video_4k \
    libchromatix_jason_s5k3m3_semco_zsl_hdr_preview_ad5816g \
    libchromatix_jason_s5k3m3_semco_zsl_hht_preview_ad5816g \
    libchromatix_jason_s5k3m3_semco_zsl_preview_ad5816g \
    libchromatix_jason_s5k3m3_semco_zsl_video_ad5816g \
    libchromatix_jason_s5k3p8sp_sunny_a3_default_preview \
    libchromatix_jason_s5k3p8sp_sunny_a3_zsl_preview \
    libchromatix_jason_s5k3p8sp_sunny_a3_zsl_video \
    libchromatix_jason_s5k3p8sp_sunny_common \
    libchromatix_jason_s5k3p8sp_sunny_cpp_liveshot \
    libchromatix_jason_s5k3p8sp_sunny_cpp_preview \
    libchromatix_jason_s5k3p8sp_sunny_cpp_snapshot \
    libchromatix_jason_s5k3p8sp_sunny_cpp_snapshot_4m \
    libchromatix_jason_s5k3p8sp_sunny_cpp_snapshot_beauty \
    libchromatix_jason_s5k3p8sp_sunny_cpp_video \
    libchromatix_jason_s5k3p8sp_sunny_postproc \
    libchromatix_jason_s5k3p8sp_sunny_preview \
    libchromatix_jason_s5k3p8sp_sunny_snapshot \
    libchromatix_jason_s5k3p8sp_sunny_snapshot_4m \
    libchromatix_jason_s5k3p8sp_sunny_video \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcrtb_lib \
    libmmcamera_arcsoft_smoothtranstion_wrapper_lib \
    libmmcamera_dbg \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_jason_imx386_ofilm \
    libmmcamera_jason_imx386_ofilm_eeprom \
    libmmcamera_jason_imx386_semco \
    libmmcamera_jason_imx386_semco_eeprom \
    libmmcamera_jason_s5k3m3_ofilm \
    libmmcamera_jason_s5k3m3_ofilm_eeprom \
    libmmcamera_jason_s5k3m3_semco \
    libmmcamera_jason_s5k3m3_semco_eeprom \
    libmmcamera_jason_s5k3p8sp_sunny \
    libmmcamera_jason_s5k3p8sp_sunny_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_jason_bu63169_ofilm \
    libois_jason_bu63169_semco \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    fingerprint.fpc.sdm660 \
    fingerprint.goodix.sdm660 \
    gatekeeper.sdm660 \
    keystore.sdm660 \
    libgf_ca \
    libgf_hal \
    libpn553_fw \
    libqminvapi \
    libthermalioctl \
    cnss-daemon \
    remosaic_daemon \
    sensors.qti \
    thermal-engine
